### ISSUE TITLE
Infinite resources loading (Fabric 1.17.1)

### ISSUE THREAD

**Issue by maicol07** [KosmX/bendy-lib#21]
When I open the game it keeps reloading the resources. When it finishes it restarts reloading

Log: [bytebin.lucko.me/VTTNs8ORtm](https://bytebin.lucko.me/VTTNs8ORtm)

**Comment by KosmX** [comment]
The issue is caused by bendy-lib (Emotecraft bending tool).

**Comment by KosmX** [comment]
[bendy-lib-2.0.3-SNAPSHOT.zip](https://github.com/KosmX/bendy-lib/files/6950946/bendy-lib-2.0.3-SNAPSHOT.zip)  
@maicol07 Try installing this library. If you do, it will overwrite the older version included in Emotecraft.  

I prefer communicating on Discord. I'm `KosmX#7620`. but it's only optional.

**Comment by maicol07** [comment]
Works! I think this can now be closed since the issue is fixed!

**Comment by KosmX** [comment]
I'll update the library in the next mod release.
