### ISSUE TITLE
Error creating mixin

### ISSUE THREAD

**Issue by AmibeSkyfy16** [KosmX/bendy-lib#25]
I have this error when starting minecraft (Im using Fabric latest version (0.12.8), 1.17.1, and curseforge launcher)
https://pastebin.com/uhAWiu11

**Comment by AmibeSkyfy16** [comment]
It is fixed, the problem occurs only at the first launch

**Comment by KosmX** [comment]
This is not even an issue of [KosmX/bendy-lib](https://github.com/KosmX/bendy-lib)  

Maybe fabric loader. Or it just couldn't open the json file
