### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Vitaki1** [KosmX/bendy-lib#29]
https://github.com/KosmX/bendy-lib/assets/136189050/7e4aa2a3-9f4c-43d3-85df-3f8ccc077fe4
How to fix it?

**Comment by KosmX** [comment]
I don't know. Please share Minecraft logs.

**Comment by Vitaki1** [comment]
Where can I get the minecraft logs from?

> I don't know. Please share Minecraft logs.

**Comment by KosmX** [comment]
https://emotes.kosmx.dev/guides/logs
