### ISSUE TITLE
Bend emote not working with custom player models

### ISSUE THREAD

**Issue by Shisuiicaro** [KosmX/bendy-lib#33]
Bend emotes doesn't work when Iuse a customizable player models skin 

![image](https://github.com/KosmX/bendy-lib/assets/126631781/7f3d6fe8-8a4e-4535-bdc3-4a488dd2a480)
![image](https://github.com/KosmX/bendy-lib/assets/126631781/cef3a936-0230-41b3-aa8d-a2ae3e3779ac)

**Comment by KosmX** [comment]
Either don't use bends or don't use custom player models. This compatibility would be really difficult to implement.
